"""empty message

Revision ID: a828c7a170c7
Revises: 252f7d1a2f3a
Create Date: 2022-10-19 02:13:40.380250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a828c7a170c7'
down_revision = '252f7d1a2f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=True))
    op.drop_index('ix_user_aud', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_column('user', 'aud')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('aud', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_aud', 'user', ['aud'], unique=False)
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
